baseURL = "https://blog.ninetailedf0x.com/"
languageCode = "en-us"
title = "NineTailedF0x Security Blog"
theme = "PaperMod"
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false
pygmentsUseClasses = true

[minify]
  disableXML = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

[params]
  env = "production"
  title = "NineTailedF0x"
  description = "Webapp pentesting and cybersec stuff"
  keywords = ["security", "pentesting", "web application security", "cybersecurity"]
  author = "NineTailedF0x"
  DateFormat = "2006-01-02"
  defaultTheme = "dark"
  disableThemeToggle = false
  ShowReadingTime = true
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowWordCount = true
  ShowRssButtonInSectionTermList = true
  ShowToc = true
  TocOpen = false
  comments = false
  hidemeta = false

  [params.label]
    text = "NineTailedF0x"
    icon = "img/avatar.png"
    iconHeight = 34

  [params.assets]
    favicon = "img/avatar.png"
    favicon16x16 = "img/avatar.png"
    favicon32x32 = "img/avatar.png"
    apple_touch_icon = "img/avatar.png"

  [params.homeInfoParams]
    Title = "I'm <span class=\"fox-name\">NineTailedF0x</span> <br>And I break web apps for a living"
    Content = "Nine tails, one fox, zero patience for bad input validation. Don't expect anything really serious here, just some security blogposts that I will write from time to time."

  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/NineTailedF0x"

  [[params.socialIcons]]
    name = "rss"
    url = "index.xml"

[markup]
  [markup.highlight]
    noClasses = false
    codeFences = true
    guessSyntax = true
    lineNos = true
    style = "monokai"
  [markup.goldmark.renderer]
    unsafe = true
